### ISSUE TITLE
Helm in air gapped environments

### ISSUE THREAD

**Issue by scult** [orange-cloudfoundry/helm-kubectl-boshrelease#6]
Hi guys,

as you requested in the call earlier, I'm going to describe potential issues I see with this BOSH release in air gapped environments. 

The obvious problem is, that helm repos, on e.g. github, can't be accessed from within an air gapped environment. One potential workaround to this would be to have your own git server within your environment and you push the required Helm repos to that git somehow. This workaround is a bit cumbersome, though since you need your local repos up to date. This would also lead to bad UX in our case, where we ship releases to customers, that should just without having to first procure a number of helm repos before they can start deploying.

Off to top of my head I can't think of a way to make this work, while keeping the release as generic as it is though, as bundling the repos with the release would require building a new release every time you need to update the repos.

Regards,
Daniel

**Comment by obeyler** [comment]
Thank you for your feedback,
The airgap mode is always complicated to keep up to date.  Creating a Helm repository is quite simple since it only requires a simple http server. There is always the problem of how to feed it so that it is up to date. But this problem also exists in Bosh release where it can also be difficult to have the latest versions updated. Harbor is a good example where I have struggled in bosh while in Helm chart the version is always updated. 
Regards Olivier

**Comment by poblin-orange** [comment]
For air gaped issues, we consider using a helm/docker registry on premise (Jfrog Container Registry). This could be populated from a big blob at startup.

To support this use case, this bosh release should include mirror url configuration

**Comment by obeyler** [comment]
I add this option to set a mirror helm repository in V14
